version: '3.8'

services:
  auth-service:
    build:
      dockerfile: ./containers/node/auth-service/Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - database

  auth-dashboard:
    build:
      dockerfile: ./containers/node/auth-dashboard/Dockerfile
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: heimdall
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
